services:
  - type: web
    name: rich-game-card-bot
    runtime: node
    plan: free
    buildCommand: bash build.sh
    startCommand: npm start
    healthCheckPath: /api/status
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
